name: Send Welcome Email

on:
  schedule:
    - cron: '50 12 * * *'  # Runs every day at 6:20 PM IST
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Python Script
        run: python send_welcome_email.py
